$iosVersion = '10.3'
platform :ios, $iosVersion
use_frameworks!

target 'Thoth_Example' do
  pod 'Alamofire'
  pod 'Thoth', :path => '../'
  pod 'Thoth/Firebase', :path => '../'
  pod 'Thoth/AppsFlyerDynamic', :path => '../'
  pod 'Thoth/AppMetrica', :path => '../'

  target 'Thoth_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iosVersion
    end
  end
end
